### ISSUE TITLE
LKV373a V4.0 TX Full dump for SPI flasher

### ISSUE THREAD

**Issue by medvm** [danielkucera/lkv373a-v4#1]
Hey! Could you send me a full TX (sender) firmware dump for the SPI flasher? My email is med.mikhail2012@ya.ru. 
Unfortunately, my device does not work after some firmware modification, and the backup contains errors. 
Thanks in advance!

**Comment by medvm** [comment]
No longer needed, I found the firmware of the required version. This issue can be closed

**Comment by danielkucera** [comment]
You can find here: https://blog.danman.eu/new-version-of-lenkeng-hdmi-over-ip-extender-lkv373a/#comment-43419
